### ISSUE TITLE
Missing sourcecode for various CPU governors

### ISSUE THREAD

**Issue by ghost** [friedrich420/Galaxy-S6-Edge-AEL-Kernel-G925F-#1]
Please share the sourceocde, especially of the mythx_plug governor.

**Comment by friedrich420** [comment]
I removed it my man from my latest build (v2)
i felt bad about what happened so i removed it.
if you want i can upload it for you 
if you are getting a compilation error, tell me what it is it i may be able to help you

**Comment by friedrich420** [comment]
and also, i never withheld the originality of your (or anyone else's) governor
the authorship is in the file my friend..

**Comment by friedrich420** [comment]
https://mega.co.nz/#!fE9TjA6T!y24MLzvmrYsNJMqgiKDceSR_CvuZonLhTya_E0XpAYk

**Comment by ghost** [comment]
Well, you can happily use that, I have absolutely no problem with that. Not that I could stop you, since everything is OpenSource. I was only "surprised" to see this after what I had to read only hours before that launch, to be honest, that kinda hit me a bit hard. As long as you publicly share the sources, be happy to use it. I didn't edit Interactive to let it rot in my cellar. OpenSource is sharing and improving. I'd also be happy if we could put the past week behind us and move on like two normal and sane people. I'm happy to even help you out with Synapse, I noticed some problems with your current configuration, it doesn't work that well together with bigLITTLE. So, what do you say? Peace and mututal respect from now on? Lets enrich the world with proper development instead of tearing each others skin off

**Comment by friedrich420** [comment]
yeah my man
its like it never happened
i updated my github with the schedulers and governors i have added so far..

**Comment by friedrich420** [comment]
about synapse its so nice of you but to enrich it it seems like an ordeal for me because i dont have the phone.. its a pain relying on others to even find the sysfs.. it took me days to find out where the schedulers were hidden lol.. i keep leaving it in mostly for the log options it gives users in case i need them to grab a log but i may completely forego it in future versions..

**Comment by ghost** [comment]
Yep, I was blind building for the first weeks myself, not a really pleasant experience, I have to agree.  When setting the CPU governor in Synapse, you have to add a second slider, targetting cpu4. Otherwise the newly set governor will only be applied for the A53 cores. Which is a problem, because the default Interactive attempts to control both clusters. That can easily create conflicts and weird scaling behaviour

**Comment by ghost** [comment]
I only realized that problem some days ago myself

**Comment by friedrich420** [comment]
this amazing phone you guys have is a pain in the butt!!
like nothing i ever dealt with before and im an exynos noob also so it makes it tougher..
i consider it a practice for the Note 5 edge lol (hopefully my next phone)

take care my man and thank you for contacting me
the reason didnt send you a pm on xda is bc i cant log into xda

take care and thank you

anytime i can help im here ;)

**Comment by ghost** [comment]
Thats only one of the many problems we ran into ;) Note 5 Edge, that one will be truely awesome. Nice to meet you personally and also likewise - If you need any help, just ask me. have fun with Exy :D
